// Auto-generated by generate_plugin_crates.py
// Registers all compiled plugin vendors with the Rack engine.

#include <rack.hpp>
#include <plugin.hpp>

using namespace rack;
using namespace rack::plugin;

// Asset path helpers (match Cardinal's custom/asset.cpp)
namespace rack {
namespace asset {
std::string pluginManifest(const std::string& dirname) {
    return rack::system::join(systemDir, "..", "..", "plugins", dirname, "plugin.json");
}
std::string pluginPath(const std::string& dirname) {
    return rack::system::join(systemDir, "..", "..", "plugins", dirname);
}
}
}

// StaticPluginLoader (from Cardinal's plugins.cpp)
struct StaticPluginLoader {
    Plugin* const plugin;
    FILE* file;
    json_t* rootJ;

    StaticPluginLoader(Plugin* const p, const char* const name)
        : plugin(p), file(nullptr), rootJ(nullptr)
    {
        p->path = asset::pluginPath(name);
        const std::string manifestFilename = asset::pluginManifest(name);
        if ((file = std::fopen(manifestFilename.c_str(), "r")) == nullptr) {
            fprintf(stderr, "cardinal: manifest %s not found\n", manifestFilename.c_str());
            return;
        }
        json_error_t error;
        if ((rootJ = json_loadf(file, 0, &error)) == nullptr) {
            fprintf(stderr, "cardinal: JSON error at %s %d:%d %s\n",
                    manifestFilename.c_str(), error.line, error.column, error.text);
            return;
        }
        json_t* const versionJ = json_string((APP_VERSION_MAJOR + ".0").c_str());
        json_object_set(rootJ, "version", versionJ);
        json_decref(versionJ);
        p->fromJson(rootJ);
    }

    ~StaticPluginLoader() {
        if (rootJ != nullptr) {
            json_t* const modulesJ = json_object_get(rootJ, "modules");
            plugin->modulesFromJson(modulesJ);
            json_decref(rootJ);
            plugins.push_back(plugin);
        }
        if (file != nullptr)
            std::fclose(file);
    }

    bool ok() const noexcept { return rootJ != nullptr; }
};

// Extern declarations for each vendor's init function and pluginInstance
extern rack::plugin::Plugin* pluginInstance__21kHz;
extern rack::plugin::Plugin* pluginInstance__8Mode;
extern rack::plugin::Plugin* pluginInstance__AS;
extern rack::plugin::Plugin* pluginInstance__AaronStatic;
extern rack::plugin::Plugin* pluginInstance__Algoritmarte;
extern rack::plugin::Plugin* pluginInstance__AmalgamatedHarmonics;
extern rack::plugin::Plugin* pluginInstance__AnimatedCircuits;
extern rack::plugin::Plugin* pluginInstance__ArableInstruments;
extern rack::plugin::Plugin* pluginInstance__Autinn;
extern rack::plugin::Plugin* pluginInstance__Axioma;
extern rack::plugin::Plugin* pluginInstance__Befaco;
extern rack::plugin::Plugin* pluginInstance__Bidoo;
extern rack::plugin::Plugin* pluginInstance__Biset;
extern rack::plugin::Plugin* pluginInstance__BogaudioModules;
extern rack::plugin::Plugin* pluginInstance__CVfunk;
extern rack::plugin::Plugin* pluginInstance__CatroModulo;
extern rack::plugin::Plugin* pluginInstance__ChowDSP;
extern rack::plugin::Plugin* pluginInstance__Computerscare;
extern rack::plugin::Plugin* pluginInstance__ESeries;
extern rack::plugin::Plugin* pluginInstance__EnigmaCurry;
extern rack::plugin::Plugin* pluginInstance__ExpertSleepersEncoders;
extern rack::plugin::Plugin* pluginInstance__Extratone;
extern rack::plugin::Plugin* pluginInstance__FehlerFabrik;
extern rack::plugin::Plugin* pluginInstance__Fundamental;
extern rack::plugin::Plugin* pluginInstance__GlueTheGiant;
extern rack::plugin::Plugin* pluginInstance__GoodSheperd;
extern rack::plugin::Plugin* pluginInstance__GrandeModular;
extern rack::plugin::Plugin* pluginInstance__HamptonHarmonics;
extern rack::plugin::Plugin* pluginInstance__ImpromptuModular;
extern rack::plugin::Plugin* pluginInstance__LifeFormModular;
extern rack::plugin::Plugin* pluginInstance__LilacLoop;
extern rack::plugin::Plugin* pluginInstance__LittleUtils;
extern rack::plugin::Plugin* pluginInstance__MSM;
extern rack::plugin::Plugin* pluginInstance__MUS_X;
extern rack::plugin::Plugin* pluginInstance__Meander;
extern rack::plugin::Plugin* pluginInstance__MockbaModular;
extern rack::plugin::Plugin* pluginInstance__Mog;
extern rack::plugin::Plugin* pluginInstance__Orbits;
extern rack::plugin::Plugin* pluginInstance__PathSet;
extern rack::plugin::Plugin* pluginInstance__PdArray;
extern rack::plugin::Plugin* pluginInstance__PinkTrombone;
extern rack::plugin::Plugin* pluginInstance__Prism;
extern rack::plugin::Plugin* pluginInstance__RebelTech;
extern rack::plugin::Plugin* pluginInstance__sapphire;
extern rack::plugin::Plugin* pluginInstance__ValleyAudio;
extern rack::plugin::Plugin* pluginInstance__Venom;
extern rack::plugin::Plugin* pluginInstance__WSTD_Drums;
extern rack::plugin::Plugin* pluginInstance__WhatTheRack;
extern rack::plugin::Plugin* pluginInstance__ZZC;
extern rack::plugin::Plugin* pluginInstance__ZetaCarinaeModules;
extern rack::plugin::Plugin* pluginInstance__admiral;
extern rack::plugin::Plugin* pluginInstance__alefsbits;
extern rack::plugin::Plugin* pluginInstance__cf;
extern rack::plugin::Plugin* pluginInstance__dBiz;
extern rack::plugin::Plugin* pluginInstance__eightfold;
extern rack::plugin::Plugin* pluginInstance__ihtsyn;
extern rack::plugin::Plugin* pluginInstance__kocmoc;
extern rack::plugin::Plugin* pluginInstance__myth_modules;
extern rack::plugin::Plugin* pluginInstance__nonlinearcircuits;
extern rack::plugin::Plugin* pluginInstance__rackwindows;
extern rack::plugin::Plugin* pluginInstance__repelzen;
extern rack::plugin::Plugin* pluginInstance__sonusmodular;
extern rack::plugin::Plugin* pluginInstance__stocaudio;
extern rack::plugin::Plugin* pluginInstance__unless_modules;

extern "C++" void init__21kHz(rack::plugin::Plugin*);
extern "C++" void init__8Mode(rack::plugin::Plugin*);
extern "C++" void init__AS(rack::plugin::Plugin*);
extern "C++" void init__AaronStatic(rack::plugin::Plugin*);
extern "C++" void init__Algoritmarte(rack::plugin::Plugin*);
extern "C++" void init__AmalgamatedHarmonics(rack::plugin::Plugin*);
extern "C++" void init__AnimatedCircuits(rack::plugin::Plugin*);
extern "C++" void init__ArableInstruments(rack::plugin::Plugin*);
extern "C++" void init__Autinn(rack::plugin::Plugin*);
extern "C++" void init__Axioma(rack::plugin::Plugin*);
extern "C++" void init__Befaco(rack::plugin::Plugin*);
extern "C++" void init__Bidoo(rack::plugin::Plugin*);
extern "C++" void init__Biset(rack::plugin::Plugin*);
extern "C++" void init__BogaudioModules(rack::plugin::Plugin*);
extern "C++" void init__CVfunk(rack::plugin::Plugin*);
extern "C++" void init__CatroModulo(rack::plugin::Plugin*);
extern "C++" void init__ChowDSP(rack::plugin::Plugin*);
extern "C++" void init__Computerscare(rack::plugin::Plugin*);
extern "C++" void init__ESeries(rack::plugin::Plugin*);
extern "C++" void init__EnigmaCurry(rack::plugin::Plugin*);
extern "C++" void init__ExpertSleepersEncoders(rack::plugin::Plugin*);
extern "C++" void init__Extratone(rack::plugin::Plugin*);
extern "C++" void init__FehlerFabrik(rack::plugin::Plugin*);
extern "C++" void init__Fundamental(rack::plugin::Plugin*);
extern "C++" void init__GlueTheGiant(rack::plugin::Plugin*);
extern "C++" void init__GoodSheperd(rack::plugin::Plugin*);
extern "C++" void init__GrandeModular(rack::plugin::Plugin*);
extern "C++" void init__HamptonHarmonics(rack::plugin::Plugin*);
extern "C++" void init__ImpromptuModular(rack::plugin::Plugin*);
extern "C++" void init__LifeFormModular(rack::plugin::Plugin*);
extern "C++" void init__LilacLoop(rack::plugin::Plugin*);
extern "C++" void init__LittleUtils(rack::plugin::Plugin*);
extern "C++" void init__MSM(rack::plugin::Plugin*);
extern "C++" void init__MUS_X(rack::plugin::Plugin*);
extern "C++" void init__Meander(rack::plugin::Plugin*);
extern "C++" void init__MockbaModular(rack::plugin::Plugin*);
extern "C++" void init__Mog(rack::plugin::Plugin*);
extern "C++" void init__Orbits(rack::plugin::Plugin*);
extern "C++" void init__PathSet(rack::plugin::Plugin*);
extern "C++" void init__PdArray(rack::plugin::Plugin*);
extern "C++" void init__PinkTrombone(rack::plugin::Plugin*);
extern "C++" void init__Prism(rack::plugin::Plugin*);
extern "C++" void init__RebelTech(rack::plugin::Plugin*);
extern "C++" void init__sapphire(rack::plugin::Plugin*);
extern "C++" void init__ValleyAudio(rack::plugin::Plugin*);
extern "C++" void init__Venom(rack::plugin::Plugin*);
extern "C++" void init__WSTD_Drums(rack::plugin::Plugin*);
extern "C++" void init__WhatTheRack(rack::plugin::Plugin*);
extern "C++" void init__ZZC(rack::plugin::Plugin*);
extern "C++" void init__ZetaCarinaeModules(rack::plugin::Plugin*);
extern "C++" void init__admiral(rack::plugin::Plugin*);
extern "C++" void init__alefsbits(rack::plugin::Plugin*);
extern "C++" void init__cf(rack::plugin::Plugin*);
extern "C++" void init__dBiz(rack::plugin::Plugin*);
extern "C++" void init__eightfold(rack::plugin::Plugin*);
extern "C++" void init__ihtsyn(rack::plugin::Plugin*);
extern "C++" void init__kocmoc(rack::plugin::Plugin*);
extern "C++" void init__myth_modules(rack::plugin::Plugin*);
extern "C++" void init__nonlinearcircuits(rack::plugin::Plugin*);
extern "C++" void init__rackwindows(rack::plugin::Plugin*);
extern "C++" void init__repelzen(rack::plugin::Plugin*);
extern "C++" void init__sonusmodular(rack::plugin::Plugin*);
extern "C++" void init__stocaudio(rack::plugin::Plugin*);
extern "C++" void init__unless_modules(rack::plugin::Plugin*);

// Master init function called by the bridge
namespace rack {
namespace plugin {

void initStaticPlugins() {
    {
        Plugin* const p = new Plugin;
        pluginInstance__21kHz = p;
        const StaticPluginLoader spl(p, "21kHz");
        if (spl.ok()) init__21kHz(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__8Mode = p;
        const StaticPluginLoader spl(p, "8Mode");
        if (spl.ok()) init__8Mode(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__AS = p;
        const StaticPluginLoader spl(p, "AS");
        if (spl.ok()) init__AS(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__AaronStatic = p;
        const StaticPluginLoader spl(p, "AaronStatic");
        if (spl.ok()) init__AaronStatic(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__Algoritmarte = p;
        const StaticPluginLoader spl(p, "Algoritmarte");
        if (spl.ok()) init__Algoritmarte(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__AmalgamatedHarmonics = p;
        const StaticPluginLoader spl(p, "AmalgamatedHarmonics");
        if (spl.ok()) init__AmalgamatedHarmonics(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__AnimatedCircuits = p;
        const StaticPluginLoader spl(p, "AnimatedCircuits");
        if (spl.ok()) init__AnimatedCircuits(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__ArableInstruments = p;
        const StaticPluginLoader spl(p, "ArableInstruments");
        if (spl.ok()) init__ArableInstruments(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__Autinn = p;
        const StaticPluginLoader spl(p, "Autinn");
        if (spl.ok()) init__Autinn(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__Axioma = p;
        const StaticPluginLoader spl(p, "Axioma");
        if (spl.ok()) init__Axioma(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__Befaco = p;
        const StaticPluginLoader spl(p, "Befaco");
        if (spl.ok()) init__Befaco(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__Bidoo = p;
        const StaticPluginLoader spl(p, "Bidoo");
        if (spl.ok()) init__Bidoo(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__Biset = p;
        const StaticPluginLoader spl(p, "Biset");
        if (spl.ok()) init__Biset(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__BogaudioModules = p;
        const StaticPluginLoader spl(p, "BogaudioModules");
        if (spl.ok()) init__BogaudioModules(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__CVfunk = p;
        const StaticPluginLoader spl(p, "CVfunk");
        if (spl.ok()) init__CVfunk(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__CatroModulo = p;
        const StaticPluginLoader spl(p, "CatroModulo");
        if (spl.ok()) init__CatroModulo(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__ChowDSP = p;
        const StaticPluginLoader spl(p, "ChowDSP");
        if (spl.ok()) init__ChowDSP(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__Computerscare = p;
        const StaticPluginLoader spl(p, "Computerscare");
        if (spl.ok()) init__Computerscare(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__ESeries = p;
        const StaticPluginLoader spl(p, "ESeries");
        if (spl.ok()) init__ESeries(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__EnigmaCurry = p;
        const StaticPluginLoader spl(p, "EnigmaCurry");
        if (spl.ok()) init__EnigmaCurry(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__ExpertSleepersEncoders = p;
        const StaticPluginLoader spl(p, "ExpertSleepers-Encoders");
        if (spl.ok()) init__ExpertSleepersEncoders(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__Extratone = p;
        const StaticPluginLoader spl(p, "Extratone");
        if (spl.ok()) init__Extratone(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__FehlerFabrik = p;
        const StaticPluginLoader spl(p, "FehlerFabrik");
        if (spl.ok()) init__FehlerFabrik(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__Fundamental = p;
        const StaticPluginLoader spl(p, "Fundamental");
        if (spl.ok()) init__Fundamental(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__GlueTheGiant = p;
        const StaticPluginLoader spl(p, "GlueTheGiant");
        if (spl.ok()) init__GlueTheGiant(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__GoodSheperd = p;
        const StaticPluginLoader spl(p, "GoodSheperd");
        if (spl.ok()) init__GoodSheperd(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__GrandeModular = p;
        const StaticPluginLoader spl(p, "GrandeModular");
        if (spl.ok()) init__GrandeModular(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__HamptonHarmonics = p;
        const StaticPluginLoader spl(p, "HamptonHarmonics");
        if (spl.ok()) init__HamptonHarmonics(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__ImpromptuModular = p;
        const StaticPluginLoader spl(p, "ImpromptuModular");
        if (spl.ok()) init__ImpromptuModular(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__LifeFormModular = p;
        const StaticPluginLoader spl(p, "LifeFormModular");
        if (spl.ok()) init__LifeFormModular(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__LilacLoop = p;
        const StaticPluginLoader spl(p, "LilacLoop");
        if (spl.ok()) init__LilacLoop(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__LittleUtils = p;
        const StaticPluginLoader spl(p, "LittleUtils");
        if (spl.ok()) init__LittleUtils(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__MSM = p;
        const StaticPluginLoader spl(p, "MSM");
        if (spl.ok()) init__MSM(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__MUS_X = p;
        const StaticPluginLoader spl(p, "MUS-X");
        if (spl.ok()) init__MUS_X(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__Meander = p;
        const StaticPluginLoader spl(p, "Meander");
        if (spl.ok()) init__Meander(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__MockbaModular = p;
        const StaticPluginLoader spl(p, "MockbaModular");
        if (spl.ok()) init__MockbaModular(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__Mog = p;
        const StaticPluginLoader spl(p, "Mog");
        if (spl.ok()) init__Mog(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__Orbits = p;
        const StaticPluginLoader spl(p, "Orbits");
        if (spl.ok()) init__Orbits(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__PathSet = p;
        const StaticPluginLoader spl(p, "PathSet");
        if (spl.ok()) init__PathSet(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__PdArray = p;
        const StaticPluginLoader spl(p, "PdArray");
        if (spl.ok()) init__PdArray(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__PinkTrombone = p;
        const StaticPluginLoader spl(p, "PinkTrombone");
        if (spl.ok()) init__PinkTrombone(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__Prism = p;
        const StaticPluginLoader spl(p, "Prism");
        if (spl.ok()) init__Prism(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__RebelTech = p;
        const StaticPluginLoader spl(p, "RebelTech");
        if (spl.ok()) init__RebelTech(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__sapphire = p;
        const StaticPluginLoader spl(p, "Sapphire");
        if (spl.ok()) init__sapphire(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__ValleyAudio = p;
        const StaticPluginLoader spl(p, "ValleyAudio");
        if (spl.ok()) init__ValleyAudio(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__Venom = p;
        const StaticPluginLoader spl(p, "Venom");
        if (spl.ok()) init__Venom(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__WSTD_Drums = p;
        const StaticPluginLoader spl(p, "WSTD-Drums");
        if (spl.ok()) init__WSTD_Drums(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__WhatTheRack = p;
        const StaticPluginLoader spl(p, "WhatTheRack");
        if (spl.ok()) init__WhatTheRack(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__ZZC = p;
        const StaticPluginLoader spl(p, "ZZC");
        if (spl.ok()) init__ZZC(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__ZetaCarinaeModules = p;
        const StaticPluginLoader spl(p, "ZetaCarinaeModules");
        if (spl.ok()) init__ZetaCarinaeModules(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__admiral = p;
        const StaticPluginLoader spl(p, "admiral");
        if (spl.ok()) init__admiral(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__alefsbits = p;
        const StaticPluginLoader spl(p, "alefsbits");
        if (spl.ok()) init__alefsbits(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__cf = p;
        const StaticPluginLoader spl(p, "cf");
        if (spl.ok()) init__cf(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__dBiz = p;
        const StaticPluginLoader spl(p, "dBiz");
        if (spl.ok()) init__dBiz(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__eightfold = p;
        const StaticPluginLoader spl(p, "eightfold");
        if (spl.ok()) init__eightfold(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__ihtsyn = p;
        const StaticPluginLoader spl(p, "ihtsyn");
        if (spl.ok()) init__ihtsyn(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__kocmoc = p;
        const StaticPluginLoader spl(p, "kocmoc");
        if (spl.ok()) init__kocmoc(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__myth_modules = p;
        const StaticPluginLoader spl(p, "myth-modules");
        if (spl.ok()) init__myth_modules(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__nonlinearcircuits = p;
        const StaticPluginLoader spl(p, "nonlinearcircuits");
        if (spl.ok()) init__nonlinearcircuits(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__rackwindows = p;
        const StaticPluginLoader spl(p, "rackwindows");
        if (spl.ok()) init__rackwindows(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__repelzen = p;
        const StaticPluginLoader spl(p, "repelzen");
        if (spl.ok()) init__repelzen(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__sonusmodular = p;
        const StaticPluginLoader spl(p, "sonusmodular");
        if (spl.ok()) init__sonusmodular(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__stocaudio = p;
        const StaticPluginLoader spl(p, "stocaudio");
        if (spl.ok()) init__stocaudio(p);
    }
    {
        Plugin* const p = new Plugin;
        pluginInstance__unless_modules = p;
        const StaticPluginLoader spl(p, "unless_modules");
        if (spl.ok()) init__unless_modules(p);
    }
}

}
}
