// Auto-generated: plugin registration via Rust FFI.
// Each vendor crate exports a C function cardinal_register_<name>().
// Calling them from Rust ensures the linker resolves cross-archive refs.

// Reference vendor crates so their native libs get linked
extern crate cardinal_plugin_aaronstatic;
extern crate cardinal_plugin_admiral;
extern crate cardinal_plugin_algoritmarte;
extern crate cardinal_plugin_amalgamatedharmonics;
extern crate cardinal_plugin_animatedcircuits;
extern crate cardinal_plugin_as;
extern crate cardinal_plugin_autinn;
extern crate cardinal_plugin_axioma;
extern crate cardinal_plugin_befaco;
extern crate cardinal_plugin_bidoo;
extern crate cardinal_plugin_biset;
extern crate cardinal_plugin_bogaudiomodules;
extern crate cardinal_plugin_catromodulo;
extern crate cardinal_plugin_cf;
extern crate cardinal_plugin_chowdsp;
extern crate cardinal_plugin_computerscare;
extern crate cardinal_plugin_cvfunk;
extern crate cardinal_plugin_dbiz;
extern crate cardinal_plugin_eightfold;
extern crate cardinal_plugin_enigmacurry;
extern crate cardinal_plugin_eseries;
extern crate cardinal_plugin_expertsleepers_encoders;
extern crate cardinal_plugin_extratone;
extern crate cardinal_plugin_fehlerfabrik;
extern crate cardinal_plugin_forsitan_modulare;
extern crate cardinal_plugin_fundamental;
extern crate cardinal_plugin_gluethegiant;
extern crate cardinal_plugin_goodsheperd;
extern crate cardinal_plugin_grandemodular;
extern crate cardinal_plugin_h4n4_modules;
extern crate cardinal_plugin_hamptonharmonics;
extern crate cardinal_plugin_ihtsyn;
extern crate cardinal_plugin_impromptumodular;
extern crate cardinal_plugin_jw_modules;
extern crate cardinal_plugin_kocmoc;
extern crate cardinal_plugin_lifeformmodular;
extern crate cardinal_plugin_lilacloop;
extern crate cardinal_plugin_littleutils;
extern crate cardinal_plugin_lomasmodules;
extern crate cardinal_plugin_lyraemodules;
extern crate cardinal_plugin_meander;
extern crate cardinal_plugin_ml_modules;
extern crate cardinal_plugin_mog;
extern crate cardinal_plugin_msm;
extern crate cardinal_plugin_mus_x;
extern crate cardinal_plugin_myth_modules;
extern crate cardinal_plugin_nonlinearcircuits;
extern crate cardinal_plugin_orbits;
extern crate cardinal_plugin_p21khz;
extern crate cardinal_plugin_p8mode;
extern crate cardinal_plugin_pathset;
extern crate cardinal_plugin_pdarray;
extern crate cardinal_plugin_pinktrombone;
extern crate cardinal_plugin_prism;
extern crate cardinal_plugin_rackwindows;
extern crate cardinal_plugin_rebeltech;
extern crate cardinal_plugin_repelzen;
extern crate cardinal_plugin_sapphire;
extern crate cardinal_plugin_sonusmodular;
extern crate cardinal_plugin_stocaudio;
extern crate cardinal_plugin_unless_modules;
extern crate cardinal_plugin_venom;
extern crate cardinal_plugin_whattherack;
extern crate cardinal_plugin_wstd_drums;
extern crate cardinal_plugin_zetacarinaemodules;
extern crate cardinal_plugin_zzc;

unsafe extern "C" {
    fn cardinal_register_21kHz();
    fn cardinal_register_8Mode();
    fn cardinal_register_AS();
    fn cardinal_register_AaronStatic();
    fn cardinal_register_Algoritmarte();
    fn cardinal_register_AmalgamatedHarmonics();
    fn cardinal_register_AnimatedCircuits();
    fn cardinal_register_Autinn();
    fn cardinal_register_Axioma();
    fn cardinal_register_Befaco();
    fn cardinal_register_Bidoo();
    fn cardinal_register_Biset();
    fn cardinal_register_BogaudioModules();
    fn cardinal_register_CVfunk();
    fn cardinal_register_CatroModulo();
    fn cardinal_register_ChowDSP();
    fn cardinal_register_Computerscare();
    fn cardinal_register_ESeries();
    fn cardinal_register_EnigmaCurry();
    fn cardinal_register_ExpertSleepersEncoders();
    fn cardinal_register_Extratone();
    fn cardinal_register_FehlerFabrik();
    fn cardinal_register_Fundamental();
    fn cardinal_register_GlueTheGiant();
    fn cardinal_register_GoodSheperd();
    fn cardinal_register_GrandeModular();
    fn cardinal_register_HamptonHarmonics();
    fn cardinal_register_ImpromptuModular();
    fn cardinal_register_JW();
    fn cardinal_register_LifeFormModular();
    fn cardinal_register_LilacLoop();
    fn cardinal_register_LittleUtils();
    fn cardinal_register_Lomas();
    fn cardinal_register_Lyrae();
    fn cardinal_register_ML();
    fn cardinal_register_MSM();
    fn cardinal_register_MUS_X();
    fn cardinal_register_Meander();
    fn cardinal_register_Mog();
    fn cardinal_register_Orbits();
    fn cardinal_register_PathSet();
    fn cardinal_register_PdArray();
    fn cardinal_register_PinkTrombone();
    fn cardinal_register_Prism();
    fn cardinal_register_RebelTech();
    fn cardinal_register_sapphire();
    fn cardinal_register_Venom();
    fn cardinal_register_WSTD_Drums();
    fn cardinal_register_WhatTheRack();
    fn cardinal_register_ZZC();
    fn cardinal_register_ZetaCarinaeModules();
    fn cardinal_register_admiral();
    fn cardinal_register_cf();
    fn cardinal_register_dBiz();
    fn cardinal_register_eightfold();
    fn cardinal_register_forsitan();
    fn cardinal_register_H4N4();
    fn cardinal_register_ihtsyn();
    fn cardinal_register_kocmoc();
    fn cardinal_register_myth_modules();
    fn cardinal_register_nonlinearcircuits();
    fn cardinal_register_rackwindows();
    fn cardinal_register_repelzen();
    fn cardinal_register_sonusmodular();
    fn cardinal_register_stocaudio();
    fn cardinal_register_unless_modules();
}

/// Register all compiled plugin vendors with the Rack engine.
/// Called from cardinal_core::init().
pub fn register_all_plugins() {
    unsafe {
        eprintln!("cardinal-rs: [register] 21kHz (21kHz)...");
        cardinal_register_21kHz();
        eprintln!("cardinal-rs: [register] 8Mode (8Mode)...");
        cardinal_register_8Mode();
        eprintln!("cardinal-rs: [register] AS (AS)...");
        cardinal_register_AS();
        eprintln!("cardinal-rs: [register] AaronStatic (AaronStatic)...");
        cardinal_register_AaronStatic();
        eprintln!("cardinal-rs: [register] Algoritmarte (Algoritmarte)...");
        cardinal_register_Algoritmarte();
        eprintln!("cardinal-rs: [register] AmalgamatedHarmonics (AmalgamatedHarmonics)...");
        cardinal_register_AmalgamatedHarmonics();
        eprintln!("cardinal-rs: [register] AnimatedCircuits (AnimatedCircuits)...");
        cardinal_register_AnimatedCircuits();
        eprintln!("cardinal-rs: [register] Autinn (Autinn)...");
        cardinal_register_Autinn();
        eprintln!("cardinal-rs: [register] Axioma (Axioma)...");
        cardinal_register_Axioma();
        eprintln!("cardinal-rs: [register] Befaco (Befaco)...");
        cardinal_register_Befaco();
        eprintln!("cardinal-rs: [register] Bidoo (Bidoo)...");
        cardinal_register_Bidoo();
        eprintln!("cardinal-rs: [register] Biset (Biset)...");
        cardinal_register_Biset();
        eprintln!("cardinal-rs: [register] BogaudioModules (BogaudioModules)...");
        cardinal_register_BogaudioModules();
        eprintln!("cardinal-rs: [register] CVfunk (CVfunk)...");
        cardinal_register_CVfunk();
        eprintln!("cardinal-rs: [register] CatroModulo (CatroModulo)...");
        cardinal_register_CatroModulo();
        eprintln!("cardinal-rs: [register] ChowDSP (ChowDSP)...");
        cardinal_register_ChowDSP();
        eprintln!("cardinal-rs: [register] Computerscare (Computerscare)...");
        cardinal_register_Computerscare();
        eprintln!("cardinal-rs: [register] ESeries (ESeries)...");
        cardinal_register_ESeries();
        eprintln!("cardinal-rs: [register] EnigmaCurry (EnigmaCurry)...");
        cardinal_register_EnigmaCurry();
        eprintln!("cardinal-rs: [register] ExpertSleepers-Encoders (ExpertSleepersEncoders)...");
        cardinal_register_ExpertSleepersEncoders();
        eprintln!("cardinal-rs: [register] Extratone (Extratone)...");
        cardinal_register_Extratone();
        eprintln!("cardinal-rs: [register] FehlerFabrik (FehlerFabrik)...");
        cardinal_register_FehlerFabrik();
        eprintln!("cardinal-rs: [register] Fundamental (Fundamental)...");
        cardinal_register_Fundamental();
        eprintln!("cardinal-rs: [register] GlueTheGiant (GlueTheGiant)...");
        cardinal_register_GlueTheGiant();
        eprintln!("cardinal-rs: [register] GoodSheperd (GoodSheperd)...");
        cardinal_register_GoodSheperd();
        eprintln!("cardinal-rs: [register] GrandeModular (GrandeModular)...");
        cardinal_register_GrandeModular();
        eprintln!("cardinal-rs: [register] HamptonHarmonics (HamptonHarmonics)...");
        cardinal_register_HamptonHarmonics();
        eprintln!("cardinal-rs: [register] ImpromptuModular (ImpromptuModular)...");
        cardinal_register_ImpromptuModular();
        eprintln!("cardinal-rs: [register] JW-Modules (JW)...");
        cardinal_register_JW();
        eprintln!("cardinal-rs: [register] LifeFormModular (LifeFormModular)...");
        cardinal_register_LifeFormModular();
        eprintln!("cardinal-rs: [register] LilacLoop (LilacLoop)...");
        cardinal_register_LilacLoop();
        eprintln!("cardinal-rs: [register] LittleUtils (LittleUtils)...");
        cardinal_register_LittleUtils();
        eprintln!("cardinal-rs: [register] LomasModules (Lomas)...");
        cardinal_register_Lomas();
        eprintln!("cardinal-rs: [register] LyraeModules (Lyrae)...");
        cardinal_register_Lyrae();
        eprintln!("cardinal-rs: [register] ML_modules (ML)...");
        cardinal_register_ML();
        eprintln!("cardinal-rs: [register] MSM (MSM)...");
        cardinal_register_MSM();
        eprintln!("cardinal-rs: [register] MUS-X (MUS_X)...");
        cardinal_register_MUS_X();
        eprintln!("cardinal-rs: [register] Meander (Meander)...");
        cardinal_register_Meander();
        eprintln!("cardinal-rs: [register] Mog (Mog)...");
        cardinal_register_Mog();
        eprintln!("cardinal-rs: [register] Orbits (Orbits)...");
        cardinal_register_Orbits();
        eprintln!("cardinal-rs: [register] PathSet (PathSet)...");
        cardinal_register_PathSet();
        eprintln!("cardinal-rs: [register] PdArray (PdArray)...");
        cardinal_register_PdArray();
        eprintln!("cardinal-rs: [register] PinkTrombone (PinkTrombone)...");
        cardinal_register_PinkTrombone();
        eprintln!("cardinal-rs: [register] Prism (Prism)...");
        cardinal_register_Prism();
        eprintln!("cardinal-rs: [register] RebelTech (RebelTech)...");
        cardinal_register_RebelTech();
        eprintln!("cardinal-rs: [register] Sapphire (sapphire)...");
        cardinal_register_sapphire();
        eprintln!("cardinal-rs: [register] Venom (Venom)...");
        cardinal_register_Venom();
        eprintln!("cardinal-rs: [register] WSTD-Drums (WSTD_Drums)...");
        cardinal_register_WSTD_Drums();
        eprintln!("cardinal-rs: [register] WhatTheRack (WhatTheRack)...");
        cardinal_register_WhatTheRack();
        eprintln!("cardinal-rs: [register] ZZC (ZZC)...");
        cardinal_register_ZZC();
        eprintln!("cardinal-rs: [register] ZetaCarinaeModules (ZetaCarinaeModules)...");
        cardinal_register_ZetaCarinaeModules();
        eprintln!("cardinal-rs: [register] admiral (admiral)...");
        cardinal_register_admiral();
        eprintln!("cardinal-rs: [register] cf (cf)...");
        cardinal_register_cf();
        eprintln!("cardinal-rs: [register] dBiz (dBiz)...");
        cardinal_register_dBiz();
        eprintln!("cardinal-rs: [register] eightfold (eightfold)...");
        cardinal_register_eightfold();
        eprintln!("cardinal-rs: [register] forsitan-modulare (forsitan)...");
        cardinal_register_forsitan();
        eprintln!("cardinal-rs: [register] h4n4-modules (H4N4)...");
        cardinal_register_H4N4();
        eprintln!("cardinal-rs: [register] ihtsyn (ihtsyn)...");
        cardinal_register_ihtsyn();
        eprintln!("cardinal-rs: [register] kocmoc (kocmoc)...");
        cardinal_register_kocmoc();
        eprintln!("cardinal-rs: [register] myth-modules (myth_modules)...");
        cardinal_register_myth_modules();
        eprintln!("cardinal-rs: [register] nonlinearcircuits (nonlinearcircuits)...");
        cardinal_register_nonlinearcircuits();
        eprintln!("cardinal-rs: [register] rackwindows (rackwindows)...");
        cardinal_register_rackwindows();
        eprintln!("cardinal-rs: [register] repelzen (repelzen)...");
        cardinal_register_repelzen();
        eprintln!("cardinal-rs: [register] sonusmodular (sonusmodular)...");
        cardinal_register_sonusmodular();
        eprintln!("cardinal-rs: [register] stocaudio (stocaudio)...");
        cardinal_register_stocaudio();
        eprintln!("cardinal-rs: [register] unless_modules (unless_modules)...");
        cardinal_register_unless_modules();
    }
}
